import os
import tempfile
from typing import Optional

from dotenv import load_dotenv
from langchain.chains import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Load environment variables from .env file
load_dotenv()

# Verify API key availability
if not os.getenv("OPENAI_API_KEY"):
    raise ValueError("Missing OPENAI_API_KEY environment variable. Please check your .env file.")

# Global variable to store the FAISS vector database instance across sessions
# Note: For multi-user environments, vector stores are typically assigned to st.session_state,
# but a global variable perfectly fits the strict functional mapping requested.
_vector_store: Optional[FAISS] = None

# Configurable constants
MODEL_NAME = "gpt-4o-mini"
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
TOP_K_RETRIEVAL = 4

def process_pdf(uploaded_file) -> str:
    """
    Saves an uploaded PDF file, processes its contents into semantic text chunks,
    generates OpenAI embeddings, and constructs a global FAISS index.

    Args:
        uploaded_file: A file-like object provided by Streamlit's st.file_uploader.

    Returns:
        str: Success message indicator.
    """
    global _vector_store
    temp_file_path = None

    try:
        # 1. Write the dynamic stream safely into a local temporary file
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp_file:
            temp_file.write(uploaded_file.read())
            temp_file_path = temp_file.name

        # 2. Extract layout text structures from the document
        loader = PyPDFLoader(temp_file_path)
        documents = loader.load()

        # 3. Dissect pages into smaller, uniform contextual fragments
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=CHUNK_SIZE,
            chunk_overlap=CHUNK_OVERLAP
        )
        chunks = text_splitter.split_documents(documents)

        # 4. Generate embeddings and establish the local vector store index
        embeddings = OpenAIEmbeddings()
        _vector_store = FAISS.from_documents(chunks, embeddings)

        return "Success: Vector database generated."

    except Exception as e:
        # Reset current context state if compilation drops out
        _vector_store = None
        raise RuntimeError(f"Failed to process and index PDF: {str(e)}")

    finally:
        # 5. Clean up local operational footprints immediately
        if temp_file_path and os.path.exists(temp_file_path):
            try:
                os.remove(temp_file_path)
            except OSError as cleanup_error:
                # Log non-fatal system runtime exceptions without halting main scope
                print(f"Warning: Temporary file cleanup failed: {cleanup_error}")

def generate_rag_response(query: str) -> str:
    """
    Retrieves relevant document fragments using semantic matching and prompts 
    ChatOpenAI to formulate a response exclusively grounded on that context.

    Args:
        query (str): The prompt submitted by the user.

    Returns:
        str: The raw text string containing the answer generated by the LLM.
    """
    global _vector_store

    # 1. Verify existence of context boundaries
    if _vector_store is None:
        raise ValueError("No active vector store found. A document context must be parsed first.")

    try:
        # 2. Configure the vector database as a top-K similarity retriever
        retriever = _vector_store.as_retriever(search_kwargs={"k": TOP_K_RETRIEVAL})

        # 3. Initialize the Large Language Model instance
        llm = ChatOpenAI(model=MODEL_NAME, temperature=0.0)

        # 4. Construct a system boundary prompt template for strict retrieval
        system_prompt = (
            "You are an expert assistant answering questions based strictly on the provided context.\n"
            "If the answer cannot be confidently derived from the context, state clearly that you do "
            "not know based on the provided document. Do not attempt to fabricate answers.\n\n"
            "Context:\n{context}"
        )
        prompt_template = ChatPromptTemplate.from_messages([
            ("system", system_prompt),
            ("human", "{input}"),
        ])

        # 5. Connect the components into a Retrieval Chain
        question_answer_chain = create_stuff_documents_chain(llm, prompt_template)
        rag_chain = create_retrieval_chain(retriever, question_answer_chain)

        # 6. Expose the query payload to the pipeline and extract the message text string
        response = rag_chain.invoke({"input": query})
        return response.get("answer", "No answer could be formulated.")

    except Exception as e:
        raise RuntimeError(f"Error handling retrieval/generation pipeline: {str(e)}")